# Generated by Django 5.0.6 on 2026-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EL', 'Electronics'), ('FU', 'Furniture'), ('CL', 'Clothing'), ('OT', 'Other')], default='EL', max_length=2)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=25)),
                ('price', models.FloatField()),
                ('insurance', models.BooleanField(default=False)),
                ('mfg', models.DateField()),
            ],
        ),
    ]
